import type { Campaign } from "@/types/campaign";
import {
  DEFAULT_CAMPAIGN_IMAGE,
  DEFAULT_CAMPAIGN_IMAGE_ALT_1,
  DEFAULT_CAMPAIGN_IMAGE_ALT_2,
  DEFAULT_CAMPAIGN_IMAGE_ALT_3,
} from "@/lib/constants";

export const ALL_CAMPAIGNS: Campaign[] = [
  {
    id: "1",
    contractId: "1",
    title: "Eco-Friendly Water Purification",
    description:
      "A compact, solar-powered water purification system for off-grid communities.",
    creator: "GABC1234ECOFRIENDLY",
    raised: 15400,
    goal: 20000,
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    image: DEFAULT_CAMPAIGN_IMAGE,
    status: "Active",
    token: "XLM",
    contributorCount: 142,
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "environment",
  },
  {
    id: "2",
    contractId: "2",
    title: "Open Source AI Education Platform",
    description:
      "Democratizing AI education with free, high-quality interactive courses for everyone.",
    creator: "GDEF5678AIEDUCATION",
    raised: 8200,
    goal: 50000,
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    image: DEFAULT_CAMPAIGN_IMAGE_ALT_1,
    status: "Active",
    token: "XLM",
    contributorCount: 67,
    category: "education",
  },
  {
    id: "3",
    contractId: "3",
    title: "Community Solar Microgrid",
    description:
      "Empowering neighborhoods to generate and share sustainable solar energy.",
    creator: "GHIJ9012SOLARGRID",
    raised: 45000,
    goal: 45000,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    image: DEFAULT_CAMPAIGN_IMAGE_ALT_2,
    status: "Successful",
    token: "XLM",
    contributorCount: 310,
    videoUrl: "https://vimeo.com/123456789",
    category: "environment",
  },
  {
    id: "4",
    contractId: "4",
    title: "Decentralized Medical Records",
    description:
      "Secure, patient-owned health records on the Stellar blockchain.",
    creator: "GKLM3456MEDRECORDS",
    raised: 3000,
    goal: 30000,
    deadline: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    image: DEFAULT_CAMPAIGN_IMAGE_ALT_3,
    status: "Active",
    token: "XLM",
    contributorCount: 28,
    category: "health",
  },
  {
    id: "5",
    contractId: "5",
    title: "Rural Connectivity Initiative",
    description:
      "Bringing affordable internet access to remote rural communities via mesh networks.",
    creator: "GNOP7890RURALNET",
    raised: 4200,
    goal: 25000,
    deadline: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    image: DEFAULT_CAMPAIGN_IMAGE_ALT_1,
    status: "Refunded",
    token: "XLM",
    contributorCount: 34,
    category: "technology",
  },
  {
    id: "6",
    contractId: "6",
    title: "Ocean Plastic Cleanup Drone Fleet",
    description:
      "Autonomous drones that collect and sort ocean plastic debris for recycling.",
    creator: "GQRS1234OCEANDRONE",
    raised: 1100,
    goal: 40000,
    deadline: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    image: DEFAULT_CAMPAIGN_IMAGE_ALT_2,
    status: "Cancelled",
    token: "XLM",
    contributorCount: 9,
    category: "environment",
  },
];
